spring:
  config:
    activate:
      on-profile: prd

  application:
    name: demo

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: demo
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect